### ISSUE TITLE
Helm enchant being double calculated

### ISSUE THREAD

**Issue by NotWarlock** [wowsims/tbc#1036]
**Describe the bug**
Gear only has 90 hit total on it + helm enchant should be 106 hit but shows 122 hit (doubled hit from helm enchant)

https://wowsims.github.io/tbc/warrior/#eJzjYtJgclITYHRg7GBkbGBk9GAKYIpgTGCsYMpMA4N39oUMIHBgkoOQNAfjDEamBYxMGkD5BkbmHYysBxiZJjAyPWBklDrF2sTIFpCTWJlaxMEkwCl1gZFLQOD1b0aJjieMSmwz/zKe/c3IxSJw/h9IvPkTo8S7h0BxoOAjoDiHwJlWJokrnUxcwgL/PzJKHN7NqMR5EywHkuYV6AcK/r7JqMQMMkVAYNofRonTnUxg/SARToFPvUxKzDfBRm0Cqr3/DKTsJlDZ9zuMcGVA6/+AyOMTmIDkil4QubyDCaintZ1JYnYLE1DPqh4mifkbgHqAht0EG722hwlsr5L4BiaWBibGDibWE0wsD5hYbzCxVjBPYGbUusDEMAqoCqo4OIBpUoLJgrHIi8tGAJjeNCESfg6GEIaKgyWYPhDk4AgREXHwhIgkOQQwZgATcQTjBEZGIQYpDgFGCUYFRgPGLkYlY1MDA1MDQ0NjAyMDQ11TIA8IgBRQzAgsYTqLkUHpMxMn2KiGNAdFmOGSs2aCwEl7oatMEkzDPc5F9jnQ20oAcpmCKw==

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Your race is set to draenei so you're giving yourself the hit buff.

We're planning to add stat breakdowns soon which should make this more intuitive.
