### ISSUE TITLE
Thunderfury does not proc during Sim

### ISSUE THREAD

**Issue by Mitch3llO01** [wowsims/tbc#1045]
**Describe the bug**
Running the sim with Thunderfury equipped does not yield any Thunderfury procs (both the attack speed slow proc, nor the 300 nature damage proc).
This is confirmed in the detailed results where there exists no Thunderfury debuffs applied, as well as checking the combat log, a quick CTRL+F yields no "Thunderfury"

**To Reproduce**
1. Equip [Thunderfury, Blessed Blade of the Windseeker]
2. Run Simulation
3. Check Detailed Results
4. No "Thunderfury" debuffs in debuff tab
5. No "Thunderfury" in combat log.

**Expected behavior**
The simulation should factor in Thunderfury's two debuffs.
- one just to show the slow speed proc is proccing
- the other to actual show the proper damage per second at the end of the sim, factoring in the 300 nature damage proc.

**Sim Links and Screenshots**
Unnecessary

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium (latest build)
 - Version 91.0.4467.0 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
TF, while we know is not DPS king, is being underrepresented by the sim. Sim needs an update.

**Comment by jimmyt857** [comment]
We never got around to a Thunderfury implementation, our first sword-using class wasn't added until just a few months ago.

This one item won't be too much work but we're fully focused on the move to wrath so I'm not sure whether it will make it in. Will leave this open just in case though.

**Comment by Mitch3llO01** [comment]
Thanks. Would love to see it implemented, if not for completion's sake. I know full well that it doesn't compete with TBC swords but still, I would like to sim the difference eventually.

**Comment by jimmyt857** [comment]
Actually found some free time to do it this morning, PR coming shortly
