### ISSUE TITLE
Raid Sim - Fails to sim when resto sham present

### ISSUE THREAD

**Issue by cloverpi** [wowsims/tbc#1050]
**Describe the bug**
When a resto shaman is in any group, the SIM fails, citing: 
Error: Unable to parse spec from player proto: {}

**To Reproduce**
1. Drop a resto sham into any group.
2. press 'DPS' to sim

**Expected behavior**
the prototype for Shams is broken

**Sim Links and Screenshots**
When dropping a Rsham into a group, console.log:
utils.js:913 Uncaught (in promise) Error: Unable to parse spec from player proto: {}
    at playerToSpec (utils.js:913:11)
    at presets.js:952:32
    at Array.map (<anonymous>)
    at presets.js:952:18
    at Array.map (<anonymous>)
    at Object.modifyRaidProto (presets.js:951:18)
    at raid_sim_ui.js:250:30
    at Array.forEach (<anonymous>)
    at RaidSimUI.modifyRaidProto (raid_sim_ui.js:245:28)
    at Sim.modifyRaidProto (raid_sim_ui.js:43:55)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by cloverpi** [comment]
Desktop app released 7 days ago seems to work just fine.  This bug report applies to the webversion.

**Comment by jimmyt857** [comment]
Thanks for the report! Fix going out soon.
