### ISSUE TITLE
Incoming HPS & Healing Cadence bug

### ISSUE THREAD

**Issue by Niklas9610** [wowsims/tbc#1060]
**Describe the bug**
The Incoming HPS & Healing Cadence numbers are resetting when leaving the field/pressing enter to update it.  I only managed to change the HPS when I saved a 0 at the start while entering the number. However changing the Healing Cadence after this also changed the HPS to the same value.

**To Reproduce**
1. Go Settings
2. Go to Encounter->Advanced and enter Brutallus preset.
3. Try to change Incoming HPS or Healing Cadence to any number without a 0 at the start or copy-pasting it.
4. Press Enter
5. the number will reset

**Expected behavior**
The field should stay with the new value instead of resetting to 0.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Windows 10 Home, OS Build 19043.1766
 - Firefox
 - 101.0.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Thanks for the report, looks like a dumb typo I made when adding this. Will have a fix out shortly.
