### ISSUE TITLE
The sim does not re-cast battle shout during battle

### ISSUE THREAD

**Issue by Rarius92** [wowsims/tbc#1086]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Could you provide a link to your settings?

**Comment by Rarius92** [comment]
I don't know how to do that.

But I think that the relevant settings are:
Duration 200sec (Battle shout only lasts 120)
Pre-cast battle shout with T2 and Sapphire

When i look at the detailed results: Buffs, "battle shout (snapshot)" has a 55% uptime, wich makes sence, because i cant get the same pre-cast battle shout once in combat.
But I think there should be a seperate buff, just called "battle shout" that should account for the remaining 45% uptime. Because there is none, i assume it does not re-cast battle shout in combat.
________________________________
Fra: jimmyt857 ***@***.***>
Sendt: onsdag 13. juli 2022 02:32
Til: wowsims/tbc ***@***.***>
Kopi: Rarius92 ***@***.***>; Author ***@***.***>
Emne: Re: [wowsims/tbc] The sim does not re-cast battle shout during battle (Issue #1086)


Could you provide a link to your settings?

**Comment by jimmyt857** [comment]
Top right corner --> Export --> Link

**Comment by Rarius92** [comment]
https://wowsims.github.io/tbc/warrior/#eJztVDFIW0EYft+fxL48EI6Y4QwI9ulgC8J7hgd28nRShBI6OYkKlga6VDrETsEqJNGIOBlFxUVdChmFLmmFoliooEMsgkZKNgvN0iEovcupdHPJ4ODHcffd9999/3AfZ1EH9bUxCCSBforREEaQoPjrGn73vDMUCosi1GJSHlgCOuThBCXh20GgAFoAnQORcmAKDbG3o5PjE+YTFowUYTG2Okc89Qt2w0kVuStYfvbjWukfK+DFktYvqrBM9n2G+HGarCa2NUt89zPsoKzpYTWydJZ49QS2T20Z+yp9D9JUu6+UIKtkSReb2LQ0OCtLg6MqvtwZzBP/e3pjYLI/V+CZvGJZeVoxP9vOkpzXSkrdlOrKNEn2LUl8Pa9afJrTLexwnvxJQoqwR/5zChQpkPA9PyTjEXXFB9OUUePUjYlhK8Zk6J7pwkvhatIuXtTWwivRq5WwGNDKmMhBS5NiQzOxLmJ4I/M9hAUgZERMjlYZZwcZ2FHPcTzHdaNOl+N2Sir3jqcWt6tW8JZh/IRhz/qC2jcunt72bF7OKez3hC6pdYDjwYbhvaiLTffOPT6D9enzH/RDp3ZvH9oQ6qf6B48piWA=
________________________________
Fra: jimmyt857 ***@***.***>
Sendt: torsdag 14. juli 2022 02:04
Til: wowsims/tbc ***@***.***>
Kopi: Rarius92 ***@***.***>; Author ***@***.***>
Emne: Re: [wowsims/tbc] The sim does not re-cast battle shout during battle (Issue #1086)


Top right corner --> Export --> Link

**Comment by jimmyt857** [comment]
You have 'Precast Shout' turned on so the initial buff lasts for most of the fight (you have it set to 200s). Then it shows the warrior casting shout once, and the buff lasts for the remainder of the fight so it doesn't cast again.
