### ISSUE TITLE
Incoming HPS changes DTPS values

### ISSUE THREAD

**Issue by Niklas9610** [wowsims/tbc#1088]
**Describe the bug**
If you enter a Incoming HPS value other than 0, the sim will increase the DTPS significantly.
Healing Cadance makes no difference though.

**To Reproduce**
1. Run a default simulation
2. Note DTPS value
3. Go to Settings
4. Click on Incoming HPS
5. Change value from 0
6. Run sim again
7. Compare DTPS value with the one before

**Expected behavior**
DTPS value should not change

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/69149335/178738772-ea6a4fb6-07fc-45d8-ad6d-e9572c562332.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 102

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
This is happening because of Ardent Defender uptime. When the healing model isn't healing you sufficiently, you get really high uptime (because you're sitting at 0% health) and therefore take less damage.
