### ISSUE TITLE
Add potion consume: Insane Strength Potion

### ISSUE THREAD

**Issue by Undertoe** [wowsims/tbc#1094]
**Is your feature request related to a problem? Please describe.**
For a very select few classes where haste isn't as strong, Insane Strength Potion may actually be a better DPS potion over Potion of Haste.  It would be nice to have this added as an option, at least to verify the delta.

**Describe the solution you'd like**
Add Insane Strength Potion to the potions options.

**Comment by jimmyt857** [comment]
This belongs in the wotlk repo.
