### ISSUE TITLE
Unable to toggle off raid buffs / debuffs

### ISSUE THREAD

**Issue by Undertoe** [wowsims/tbc#1097]
**Describe the bug**
Most buffs do not have an option for "Nothing", making it impossible to toggle the buffs off

**To Reproduce**
1. Go to "Settings"
2. Enable Melee Crit
3. Hover over Melee Crit
4. You now cannot remove it

**Expected behavior**
There should be a way to clear these buffs so that you can verify the effectiveness of them, as well as check specific comp damage.

**Comment by Undertoe** [comment]
I also don't seem to be able to toggle between buffs in some cases:

Dmg% unable to change from Sanctified Retribution

**Comment by jimmyt857** [comment]
I think this belongs in the wotlk repo.  ;)
