### ISSUE TITLE
PI stacking with BL in Boomkin sim

### ISSUE THREAD

**Issue by wrapxd** [wowsims/tbc#144]
Hello!
This is probably a known issue, but just in case: the haste effects from Power Infusion and Bloodlust/Heroism shouldn't stack, only the mana cost part of PI works.
Please make it so that PI is applied after BL if the fight is long enough.

Example:
![image](https://user-images.githubusercontent.com/96955018/147858054-7a735569-37cf-48c6-80ef-baac0cfd2bb1.png)
- while both BL and PI are up the SF casts take 1.5s, as soon as PI fades it goes up to 1.8s

**Comment by jimmyt857** [comment]
Thanks for pointing this out! In the next few days we'll be adding the ability to pick all cooldown timers if desired, but your suggestion for the default behavior is definitely a good one. Most people aren't going to notice that (including us apparently).

**Comment by jimmyt857** [comment]
Haste portions of PI and Bloodlust now correctly no longer stack, and by default they will not be used together. Picking custom CD timings is also added so you can force an overlap if you really want to.
