### ISSUE TITLE
Companion Addon to Import Character

### ISSUE THREAD

**Issue by generalwrex** [wowsims/tbc#262]
**Is your feature request related to a problem? Please describe.**
Its time consuming and slightly annoying to manually input your gear, gems, and enchants.

**Describe the solution you'd like**
A companion addon, to export your character, and then import it into the website.

**Describe alternatives you've considered**
N/A

**Additional context**
I could potentially create the addon if someone could add in the website part to import a data string. However I cant seem to find the proper API for TBC Classic, if someone could point it out for me?

**Comment by generalwrex** [comment]
I would like to make the addon generalized to work with all these different simulator websites floating around too!

**Comment by jimmyt857** [comment]
This is something we've talked about before and definitely would be cool to have, unfortunately its not a top priority for us with so many sims left to write. We could definitely add the UI if you're able to write a addon for us! Make sure you join our discord (linked on the readme for this repo) so we can communicate better.

**Comment by generalwrex** [comment]
For people following this that are not in the Discord.  The addon is in the works and is in testing!

**Comment by jimmyt857** [comment]
Resolving this issue, the addon is now implemented and importing to the sim is fully functional!
