### ISSUE TITLE
Enhancement Sim Features Request

### ISSUE THREAD

**Issue by kdevolder** [wowsims/tbc#266]
Below are additional options to the sim I am hoping could be added, or at the very least on the Gear sheet to be able to just have the Bonus Stats for Spell Crit and Spell Hit to be added.  My guild has a "Bonus Shaman" who sometimes heals when the guild needs him to and sometimes plays as an Enhance in a suboptimal group.

Settings:

Other Buffs:
Totem of Wrath
Moonkin Aura
^Idol of the Raven Goddess
Eye of the Night
Chain of the Twilight Owl

Consumes:
Flask of Supreme Power

Gear:

Bonus Stats:
Spell Crit
Spell Hit

EP Weights:
Spell Crit
Spell Hit

**Comment by jimmyt857** [comment]
Thanks for the request! Added all of these (and wrath of air totem) in #267

**Comment by kdevolder** [comment]
You guys are the best, thank you so much.
