### ISSUE TITLE
Items incorrectly marked as P3 item

### ISSUE THREAD

**Issue by pajlada** [wowsims/tbc#303]
**Describe the bug**
The items [Vindicator's Pendant of Subjugation](https://tbc.wowhead.com/item=35319) and [Vindicator's Pendant of Reprieve](https://tbc.wowhead.com/item=35317) are marked as available in P3 when simming necklaces, however they are not available in vendors and are marked in wowhead as "Added in content phase 4"

**To Reproduce**
1. Go to https://wowsims.github.io/tbc/shadow_priest/
2. Select "Gear" tab
3. Click necklaces
4. Select Phase 3 in the top right directory
5. See that **Vindicator's Pendant of Subjugation** and **Vindicator's Pendant of Reprieve** are available (and at the top)

**Expected behavior**
**Vindicator's Pendant of Subjugation** and **Vindicator's Pendant of Reprieve** should not be available, as they will be available in Phase 4 instead of Phase 3

**Sim Links and Screenshots**
Showing the error
![image](https://user-images.githubusercontent.com/962989/152386200-3d1cabc6-baca-46ea-b209-4327a4f65feb.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jimmyt857** [comment]
Thanks for the report! This should be fixed now.
