### ISSUE TITLE
Import Gear from Warcraftlog

### ISSUE THREAD

**Issue by L3xow** [wowsims/tbc#343]
**Is your feature request related to a problem? Please describe.**
No, actually not, its more of a convenience feature.

**Describe the solution you'd like**
So, theres the thing with Warcraftlogs, where they log all the Gear, Sockets and Enchants a Player has. Wouldn't it be possible, to build a feature to read that kind of gear constellation and import it into the wowsim? Pages like IronForge.com also showed the latest Gear and I think its also read from the logs.

**Describe alternatives you've considered**
Maybe make it possible to import it from an Addon like ItemRack or try to develop an selfmade addon. Since WoW Classic will be viable for a long time it should safe a lot of time for most of us.

**Additional context**
-/-

**Comment by jimmyt857** [comment]
Someone is already working on an in-game addon for this (#262). Hopefully it should be coming pretty soon!

Importing from WCL is a great idea which we definitely want to have, just a matter of when we can spare the time to build it.

**Comment by jimmyt857** [comment]
This is now being tracked in #702
