### ISSUE TITLE
Detailed Results -> Expand hunter pet lists subnodes/subrows under the wrong parent node/row

### ISSUE THREAD

**Issue by nodoxxplz** [wowsims/tbc#344]
**Describe the bug**
After running a DPS simulation for a hunter on https://wowsims.github.io/tbc/hunter/ , the "detailed results" tab/view shows an arrow next to the pet type/name. When clicking this, the expanded nodes are not grouped under the pet parent node, but rather under separate irrelevant nodes ("Ravager - Attack (Main Hand)" & "Ravager - Kill Command" are grouped under "Steady Shot" , while "Ravager - Gore" & "Ravager - Bite" are grouped under either "Multi-shot" or "Attack", depending on whether the "Melee Weave" setting is selected or not).

**To Reproduce**
1. Go to https://wowsims.github.io/tbc/hunter/ 
2. (Optionally go to "Settings" and deselect "Melee Weaving")
3. Press the "DPS" button to calculate
4. Go to "Detailed Results"
5. Click the pet row ("Ravager" by default)
6. Observe that the subnodes/subrows for the Ravager are grouped under irrelevant/incorrect columns

**Expected behavior**
I'd expect them to either group under the "Ravager"/pet row, or under the "Attack" row

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/98270811/153087973-c0cbc607-c1a7-497a-8adc-ab21a266f1bf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  97.0.4692.99

**Additional context**
Thanks for a great sim ::)

**Comment by jimmyt857** [comment]
This is working as intended, what's actually happening is that the rows are sorted by DPS. You can click on the column names to change the sorting.

Ignoring the sorting for sub-actions and keeping them grouped is an option, though. We'll have to think on this and decide which way makes more sense. Good suggestion!

**Comment by jimmyt857** [comment]
This is now implemented. Thanks for the suggestion!
