### ISSUE TITLE
Snapshot T4 2-set bonus

### ISSUE THREAD

**Issue by Inzane903** [wowsims/tbc#348]
Hey!

There is already the feature of the BS snapshot in the enhance shaman sim. 
It would be really nice if you could add a similar option, just for the shaman T4 2-set bonus as snapshot aswell. Probably needless to say, but this bonus adds 12 strength to Strength of Earth Totem.

Other than this, great work on the sim! :D

**Comment by jimmyt857** [comment]
Thanks for the suggestion. This has been added now!
