### ISSUE TITLE
Hunter Sim Fel Mana Potion

### ISSUE THREAD

**Issue by Hockie123** [wowsims/tbc#383]
Are fel mana potions going to be implemented? They are much better than the regular mana potions for hunters. Allows us to mana pot earlier for a guarenteed 3200 mana. Can be used when -1500 to -2000 mana therefore getting your potion back off CD sooner.

Thanks.

**Comment by jimmyt857** [comment]
Thanks for the request, Fel Mana Potions have now been added!
