### ISSUE TITLE
Error when trying to run sim with WF testing

### ISSUE THREAD

**Issue by Alaskanhike** [wowsims/tbc#394]
**Describe the bug**
I keep getting an error when trying to run the sim. Seems related to Twist Winfury and Twist Fire Nova both being enabled, as the issue does not happen when I disable 1 of the 2 options. The error I see in the console is panic: No timeslot found for air totem

Copy of what I see in the console window
`Raid sim request: {"raid":{"parties":[{"players":[{"name":"Player","race":"RaceTroll10","class":"ClassShaman","equipment":{"items":[{"id":32235,"enchant":29192,"gems":[32409,24058]},{"id":30022},{"id":32581,"enchant":28888},{"id":32323,"enchant":34004},{"id":32252,"enchant":24003,"gems":[24027,24027,24058]},{"id":32574,"enchant":27899},{"id":30189,"enchant":33995},{"id":30040,"gems":[24054,24054]},{"id":30900,"enchant":29535,"gems":[24027,24027,24031]},{"id":30104,"enchant":28279,"gems":[24027,24027]},{"id":28757},{"id":32497},{"id":29776},{"id":29383},{"id":32262,"enchant":22559},{"id":29996,"enchant":22559},{"id":33505}]},"consumes":{"flask":"FlaskOfRelentlessAssault","food":"FoodRoastedClefthoof","scrollOfAgility":5,"scrollOfStrength":5,"defaultPotion":"HastePotion","defaultConjured":"ConjuredFlameCap","drums":"DrumsOfBattle"},"bonusStats":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"buffs":{"blessingOfKings":true,"blessingOfWisdom":"TristateEffectImproved","blessingOfMight":"TristateEffectImproved"},"talentsString":"02-502500210502133531151-05005301","cooldowns":{},"enhancementShaman":{"rotation":{"totems":{"earth":"StrengthOfEarthTotem","air":"GraceOfAirTotem","fire":"MagmaTotem","water":"ManaSpringTotem","twistWindfury":true,"windfuryTotemRank":5,"twistFireNova":true},"primaryShock":"Earth","weaveFlameShock":true},"talents":{"concussion":2,"ancestralKnowledge":5,"thunderingStrikes":5,"enhancingTotems":2,"shamanisticFocus":true,"flurry":5,"improvedWeaponTotems":2,"elementalWeapons":3,"mentalQuickness":3,"weaponMastery":5,"dualWieldSpecialization":3,"unleashedRage":5,"stormstrike":true,"shamanisticRage":true,"totemicFocus":5,"naturesGuidance":3},"options":{"waterShield":true,"bloodlust":true,"delayOffhandSwings":true,"mainHandImbue":"ImbueWindfury","offHandImbue":"ImbueWindfury"}}},{},{},{},{}],"buffs":{"sanctityAura":"TristateEffectImproved","battleShout":"TristateEffectImproved"}},{"players":[{},{},{},{},{}],"buffs":{}},{"players":[{},{},{},{},{}],"buffs":{}},{"players":[{},{},{},{},{}],"buffs":{}},{"players":[{},{},{},{},{}],"buffs":{}}],"buffs":{"arcaneBrilliance":true,"divineSpirit":"TristateEffectImproved","giftOfTheWild":"TristateEffectImproved"}},"encounter":{"duration":180,"durationVariation":5,"executeProportion":0.2,"targets":[{"armor":7700,"debuffs":{"judgementOfWisdom":true,"improvedSealOfTheCrusader":true,"misery":true,"curseOfElements":"TristateEffectImproved","bloodFrenzy":true,"exposeArmor":"TristateEffectImproved","faerieFire":"TristateEffectImproved","sunderArmor":true,"curseOfRecklessness":true,"exposeWeaknessHunterAgility":1000}}]},"simOptions":{"iterations":3000,"debugFirstIteration":true}}
sim_worker.js:51 panic: No timeslot found for air totem`

**To Reproduce**
https://wowsims.github.io/tbc/enhancement_shaman/#eJzlUj1LA0EQzZu7jZdDZIkpztgkKSQIkbscV3tgYylWllpoZaNVtAqCEm0Uq2ijpYVFCgvhRATxC5sICicKSUAlJFikUTCJuJuIf8JhGN7svHkzMKsHNcQoSeHgPmgLFL1TVxCcmJ9Zml3UQrwnegKd83oTRu4FieBOG18edJVf1qBr/OIbhl+R6LwF436d9H7eEtxzD4nQkwfhkq7xU0FsPkr0XodxK4i93K8JwQ8PwkXbUQNG6e2vreTJuXlB/nwWtO6jmPtQlrHRlrFYlfHqVcquifl7BYkOa12k8soqJSIFUq9JLRPziWUUH5QHhqsI/BNbFvflZNA2JvWI3icSGIghiSlmdnB4hFOGZcFy8v7Ig4mPcAClAOUY7AzKNdgWIU8ogvlQorrUSMJQY+oG4mY65ZhpxzTTlimAZduObVmOlRKZ6dimtYtAYizU2SU758a7W0Xcgd0daTej4aFuMXLqhgd/1yMX4zRBU5jGQqfobro/wjVykQ==

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/tbc/enhancement_shaman/#eJzlUj1LA0EQzZu7jZdDZIkpztgkKSQIkbscV3tgYylWllpoZaNVtAqCEm0Uq2ijpYVFCgvhRATxC5sICicKSUAlJFikUTCJuJuIf8JhGN7svHkzMKsHNcQoSeHgPmgLFL1TVxCcmJ9Zml3UQrwnegKd83oTRu4FieBOG18edJVf1qBr/OIbhl+R6LwF436d9H7eEtxzD4nQkwfhkq7xU0FsPkr0XodxK4i93K8JwQ8PwkXbUQNG6e2vreTJuXlB/nwWtO6jmPtQlrHRlrFYlfHqVcquifl7BYkOa12k8soqJSIFUq9JLRPziWUUH5QHhqsI/BNbFvflZNA2JvWI3icSGIghiSlmdnB4hFOGZcFy8v7Ig4mPcAClAOUY7AzKNdgWIU8ogvlQorrUSMJQY+oG4mY65ZhpxzTTlimAZduObVmOlRKZ6dimtYtAYizU2SU758a7W0Xcgd0daTej4aFuMXLqhgd/1yMX4zRBU5jGQqfobro/wjVykQ==)

![image](https://user-images.githubusercontent.com/22381493/154819080-dfdc8295-7f8b-489c-a0e9-22eeddaaa40c.png)

**Desktop (please complete the following information):**
Windows - Chrome - 98.0.4758.102

**Additional context**
I am also available via discord if needed Zulprijin#6254 if you have any question

**Comment by jimmyt857** [comment]
Thanks for reporting, this should be fixed now!
