### ISSUE TITLE
Missing items: [Blade of Unquenched Thirst]

### ISSUE THREAD

**Issue by Jazz405** [wowsims/tbc#401]
I'm toying around with spellhance stuff and I'd appreciate it if Blade of Unquenched Thirst could be added.
[Blade of Unquenched Thirst](https://tbc.wowhead.com/item=31193/blade-of-unquenched-thirst "https://tbc.wowhead.com/item=31193/blade-of-unquenched-thirst")

From Classic Wow Armaments Discord:
Name                                        |  Hits   | Procs | Chance| ICD
 Blade of Unquenched Thirst   │  2500 │   51  │  2%    │ 0  
100% + SpellDamage Scaling Coefficient

**Comment by jimmyt857** [comment]
Added!
