### ISSUE TITLE
Hit Scope

### ISSUE THREAD

**Issue by swayerman** [wowsims/tbc#408]
In the hunter sim the hit scope is correctly being factored into the sim, however the hit rating isn't being applied to the stat break down in the bottom left of the screen.

**Comment by jimmyt857** [comment]
Thanks for the report! This is actually working as intended; the ranged scope only gives ranged hit, and the stats panel only shows static stats similar to what would appear in the in-game character pane.

Do you think we should change this behavior?

**Comment by jimmyt857** [comment]
Marking this closed since there don't seem to be any more comments.
