### ISSUE TITLE
Detailet results - missing trinket aura

### ISSUE THREAD

**Issue by Izuelazug** [wowsims/tbc#417]
Hello, _**I dont know if is calculating with use trinkets or not, bcs in Detailet results cant see trinket aura using at start fight**- SOLVED WITH REFRESH SITE

 _**.. and with this point will be great to add on use trinkets to Settings -> cooldown to use these trinkets .. Bbc with double use trinkets I am using with Heroism so I have 40sec trinekts with Hero ... its huuuge and ofc timing for Hero not from Start.**_ - Solved with refresh site, dont understand but its ok thanks a lot :)

thanks Izuelazug

**Comment by jimmyt857** [comment]
Trinkets with active effects should already be included in Settings --> Cooldowns, are you not seeing them?

**Comment by jimmyt857** [comment]
Looks like your edits indicate that this issue resolved on its own. Going to close this thread, feel free to reopen if the issue occurs again.

**Comment by Izuelazug** [comment]
Thanks
