### ISSUE TITLE
Void Spheres do not fulfill meta gem requirement

### ISSUE THREAD

**Issue by eighchbar** [wowsims/tbc#428]
See the following set:
https://wowsims.github.io/tbc/balance_druid/#eJzlkb1LA0EUxDNv78K6KCxRYQ0I4aooBC53BLQypaWlZSwUCwuxUqtDC1EbQdCYdKKdYGoPbWy0MxYifpGggRAUYyNCVNxN/gwfyxS/Gd48WEEcMcGRRA6zmEe8ZK0gOjE3tTS9wLlEPISQ8vAZau0FTrQV4miThCUfvw0vvkK9VTX/CqEtweVTBep3hUSv3NXeeQinq9X2jN0jdz6gyuvksLuWSed1pvkA0S2bjc72Tqyg+fUpHHZzb2pqT1DVbXKi4TH00/WfL0bLFaMnNaP772bhQQOqWIKIaLL6A6evRAjIuiBcEepkL9ItMFxH5J/MssUh4Y0Ki1sSsRS3JSlKsCRce4RlMc4m7EnKMf31bNEOgC/YAdEWsTyxOInIBgYzadf1PD/tZVw/7Wc8I+lUKuO5ru8XEHGGutpdwUx2oLBn5nIs1t9hfWdZRTFujlBI0B+2V2W8

Chaotic Skyfire Gem requires at least 2 blue gems to activate. The shoulders have 1 purple and the shoes have 2 Void Spheres, so it should be active, but isn't.

**Comment by jimmyt857** [comment]
This got fixed a few days ago but I think we forgot to comment. Will mark this resolved for now, feel free to reopen if you still have any issues.
