### ISSUE TITLE
[Hunter] Aspects not displayed correctly in Detailed Results

### ISSUE THREAD

**Issue by Kruemmelkeks** [wowsims/tbc#441]
When simming different setups I noticed the activity time of the aspects (Hawk + Viper) does not add up to 100%. See for example to following screenshot, Uptime of Aspect of the Hawk and Uptime of Viper add to to 100,22%. 

![image](https://user-images.githubusercontent.com/37963123/155882572-25c4a70e-a5d3-4ce5-8b96-78e2571688c7.png)

Second, in the timeline view sometimes the active Aspect is missing in the tooltip. I noticed this is always the case if I switch back from Viper to Aspect of the Hawk hwn regaining enough mana. Seems to be just a display issue though.

![image](https://user-images.githubusercontent.com/37963123/155882673-68165c53-d669-4f4b-b836-d61fe98b8ee1.png)

This is the setup I used:
https://wowsims.github.io/tbc/hunter/#eJzlkr9LHEEUx/N9u3OMQ6LjCmZyIeFcLA7BuLtmwaTZLS0vnWVEElJYWanVRZtTCImd2pgyYBNShDMXVAzkh+mMSQSVJOCJeiAI6hUiZuZOUfMv5MvwePOZN495856wOdLkSI5xUD9lYefBXoCSS2wIiUxv98CjPp6QlFyAkLJ0BJXbgJuYOMbCEYQtSzuGz5WgVv5ovriOr+sQXH4sQi2PkGiQmztQHwpwa77volzAz1VzvKjhkj7m8r2+mh0mcVVO7ekEawXoJa7JWc1/bcK1zFbKk22o8tp5gC0PNowt/zb2+TRp+6loUr9+SurZsEk9todT7532fszAvZUna54oSyxH+Ez0imBqtnKgFaBlC1f+Ew0mOCQput8jmrUHf3LCaCa6117RtyhG5771oIq3IyfNmYSiFEszj7aIOuzY6kSGdeEhe8L6KQfoqXkJlqzX46Ijmx5XtBulb48iFfqB5wWeH/qh5wfB3XbfC/1WLwwNDLxwEj2iTli8eN3h1RfeiYXUPX37BpcJPxz/h5juXyBJUctHGlMnZ7oQ7bbVVLz5vvhGtbIvkXOzyjrysSKn1nxGChnSdenR+AskjpLA

**Comment by jimmyt857** [comment]
Thanks for the report! Found both of the bugs, should be fixed now with #446
