### ISSUE TITLE
Rogue dmg sims the same as 1 target even though there are 2 targets

### ISSUE THREAD

**Issue by szymczycha** [wowsims/tbc#461]
**Describe the bug**
Adding a second target on the Rogue sim doesn't change damage,

**To Reproduce**
1. Sim any setup with 1 target
2. Sim the same setup with 2 targets 

**Expected behavior**
There should be a dps increase since during blade flurry rogue hits 2 targets and not one 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera GX
 - Version - The one right now on the browser

**Comment by jimmyt857** [comment]
Thanks for the report! This is a known issue, the 2nd hit from blade flurry simply hasn't been implemented yet since rogue sim is still a WIP. We're getting there! ;)
