### ISSUE TITLE
Missing items: [Wicked Edge of the Planes] for OH

### ISSUE THREAD

**Issue by acerd44** [wowsims/tbc#488]
[Links to [TBC Wowhead](https://tbc.wowhead.com/items "https://tbc.wowhead.com/items") for each item:
](https://tbc.wowhead.com/item=28433/wicked-edge-of-the-planes)

You can wield Dragonstrike in offhand but not WEotP, probably not that important but just curious how 2x WEotP or talon+WEotP would look like

**Comment by jimmyt857** [comment]
Thanks for the report! We'll be making a pass soon and updating all of the MH --> 1H transitioning items. Dragonstrike was added early because it has bis or near-bis potential and the proc needed to be simmed.

Will leave this thread open until we actually make these changes.

**Comment by jimmyt857** [comment]
This should be fixed now.
