### ISSUE TITLE
Missing items: Gloves of Pandemonium

### ISSUE THREAD

**Issue by mbriden** [wowsims/tbc#531]
Links to [TBC Wowhead](https://tbc.wowhead.com/items "https://tbc.wowhead.com/items") for each item:
[Gloves of Pandemonium](https://tbc.wowhead.com/item=31149/gloves-of-pandemonium "https://tbc.wowhead.com/item=31149/gloves-of-pandemonium")

**Comment by jimmyt857** [comment]
Added!
