### ISSUE TITLE
Adding some buffs 

### ISSUE THREAD

**Issue by rawseki** [wowsims/tbc#533]
Could you add hunter beast mastery buffs (+3%dmg) and kreeg's stout?
Thanks you for the good work with the sim!

**Comment by lologarithm** [comment]
which sim is missing these options?

**Comment by rawseki** [comment]
Shadow priest sim. Sorry thought that would have been known, clicked this
link from that sim. https://wowsims.github.io/tbc/shadow_priest/#

**Comment by jimmyt857** [comment]
Ferocious inspiration has been added. Kreeg's Stout Beatdown was already there (next to food).
