### ISSUE TITLE
More haste details

### ISSUE THREAD

**Issue by grzegorzdec** [wowsims/tbc#539]
**Is your feature request related to a problem? Please describe.**
It's not easy to optimize haste cooldowns

**Describe the solution you'd like**
As a mage, I'd like to see current haste on DPS Timeline and have information of wasted time because of the gcd limit below DPS on the left site after calculation (same place as TPS now)

**Describe alternatives you've considered**
no idea

**Additional context**
have to manage lots of haste cds like bl, pi, skull trinket, drums, racial etc

**Comment by jimmyt857** [comment]
This is a cool idea! Unfortunately we're still busy with a lot of other things, like writing the rest of this sims. If you or anyone you know would like to write the code for this we could provide guidance. Otherwise it might be awhile before we can get to this.

**Comment by jimmyt857** [comment]
With the upcoming move to wrath, it looks like there won't be enough time to even consider something like this. Can reopen in the wrath repo if it's still an issue.
