### ISSUE TITLE
Stormstrike present in log/results when talent not selected

### ISSUE THREAD

**Issue by Jazz405** [wowsims/tbc#551]
**Describe the bug**
Enhance Shaman 
When StormStrike is not selected in the talents, it's still being included in the sim

**To Reproduce**
1. Remove StormStrike from selected Talents
2. Run Sim
3. Check logs
4. Stormstrike will still be present

**Expected behavior**
Would expect stormstrike to not be there. Also might need to look at dps with/without stormstrike. Since Stormstrikes included the dps should be roughly the same but its affecting the sim in a weird way it seems

**Additional context**

**Comment by jimmyt857** [comment]
Thanks for reporting, this should be fixed now!
