### ISSUE TITLE
Biznicks 247x128 Accurascope does not take effect

### ISSUE THREAD

**Issue by comcaptain** [wowsims/tbc#573]
**Describe the bug**
When using the simulator to simulate hunter, attaching Biznicks 247x128 Accurascope does not increase hit in bottom left corner

**To Reproduce**
I think this is obvious

**Expected behavior**
Attaching Biznicks 247x128 Accurascope should add 30 hit

**Sim Links and Screenshots**
https://wowsims.github.io/tbc/hunter/#eJzjYuFg1GASEuBgnMHIVMHUwMiyg5F1AiOT1BTWJka2gJzEytQiDkYBJqkjjFwCAk3tTBIdTxiV2Gb+ZTz0m5GLReD8P5D4vE+MEu8eAsWBgiBxDoHDfxglrnQycQkLzAHKHd7NqMQJlHgERly8AkeA0pc6mZSY74G5M4FqGpqBXIiht/6ABOcCBe8/Y4QICggs+MgoMWED0I47uxn//AApe/IKRH59AiKPPwWRz/+C7J7zi1Git5kJyHrbwgRlXQBa+LqPUYlvAxNLAxNrBxPjCSamCmatGUwMowArqOLgYHQAxrwEk1UylwowDTAazpoJAjvtLY3B4LJ9BLPHF+ZAiPBLeyENDlYBRgkmBVYNVgOmF0xMFiwOzB6MAawRjAmsBawVTB2MjMCktYCRVUqQg02AWYJREWLVB3sNuS5GBVNDIwMDIwNDU0NTA0MjIxNjQwNTQ10DUwNToKCRgeksRgYlM06wjoY0B6heEQdJiP0n7YUkIZIs+xwkmIR4QE5WYAxgAtrOCADbg3ns

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.2.1
 - Browser: Microsoft Edge
 - Version  99.0.1150.52 ARM64

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Thanks for the report! This is actually working as intended; the hit is not shown in the stats panel because it is ranged-hit only, and doesnt apply to all hunter abilities (like melee weaving). If you look in Detailed Results you can see that the bonus hit is correctly being applied to all ranged attacks.
