### ISSUE TITLE
Hunter Sim calculates EP for hit based on 16%

### ISSUE THREAD

**Issue by WaDaFruCK** [wowsims/tbc#639]
**Describe the bug**
Hunter simulator calculates EP for hit values as though hunters need 16% hit.

**To Reproduce**
Create a sim, and calculate EP.
Manually adjust hit using bonus stats to 16% and recalculate.

**Expected behavior**
EP should be based on a 9% hit cap

**Comment by jimmyt857** [comment]
Thanks for the report! EP calculations for hit are really difficult. What you're seeing though is that we try to calculate the value of your 'last point of hit' so ideally we would never show a value of 0. In practice, you'll see 0 at certain thresholds over the actual 9% cap.

If you want a specific EP for hit you can always set it manually in Settings (top-right cog icon).

**Comment by WaDaFruCK** [comment]
If you have 150 hit, it still expects an EP of 4.x or some insanely high number, whereas with 16% exactly, it puts the ep at exactly 0%, despite the last point of hit being identical. Values above 16% take the EP value of hit negative, whereas values below go exceedingly positive. Interestingly, anything from 0%-9% works and sims appropriately, only when you go above 9% does the EP value completely break, until the 16% breakpoint.

**Comment by jimmyt857** [comment]
Here's a link with ~15.3% (which is not 16% exactly) and results in ~0 EP: https://wowsims.github.io/tbc/hunter/#eJzNUr9LW1EUznfeu+H5sOUaHa4ZSvroEArCfU+fWJf3Rse4ZewP2smhdEo7RV2STgUXIyL+CRkNwVBQ0Q5dbJUWQqMQS7sJFeJgoOfmibObflwO93znfOd8w3FtB3nKSAeroBKVYW9BfAJlv4olpAsLL96/fudAcg5Xyn9tqEoXXrrdRK0P15Z7Z4av/YT6ccr81SW45D6QO9tQ36vkWSYdlbss3GnCG+KUX49JR7a6UIdVYv3hMVR5mQZzjWBYrptp3MYDWb5yDtX5fSM3LVIudqB67cRMv2nMHJ2Y2BvEjVMT98/MopVfUOt1uCn+d0+gjhvwHtbJLhMqhAOikvX0gFL3GZ9fxndt4bb44DiI+WQUzb5yn/DxwF+rGTSiZ5MDfIuK1tyFNZ/Qf6NM3hESinIiLzT9IZqxY2sOBVHEc/FWlKgC8E1uQmRHnLS0FB4nq86j/KOPyIV+oHWg/dAPtR8EU5O+Dv0JHeqQyUCHa0h500MDRflNfK0di8eT/V+izHhStFuxosywsZxDgXg7/gPo84Ak

There is no condition where we hard set an EP value for any stat.

**Comment by WaDaFruCK** [comment]
In that example, 15.28% hit sims an EP on hit of ~.11.
Increasing the hit bonus/offset to 152 increases the hit to 16.04%, which then creates an EP on hit of almost exactly 0 (.03).

In both situations, the valuation of hit should either be identical (if simming as the last point of hit), or 0, as the hit cap for hunters is only 9%. 

For reference, if we do similar tests with the enhancement shaman sim (remove off hand to negate EP from off hand having a higher hit cap, or calculate based on OH hit cap), the value begins to go negative once past the main hand hit cap (accounting for talents, or removing them), equaling out to almost exactly 0 right at 9% hit cap, in an identical behavior to the hunter sim equaling out right at 16%, conveniently the hit required for spells.

Closing the issue here as it may not be a bug, but definitely has some strange behavior as compared to other sims with hunter specifically around the 16% mark, which is the spell hit cap, and is not analogous to the enhancement sim behavior.
