### ISSUE TITLE
TBC Enhancement Shaman Sim Bug

### ISSUE THREAD

**Issue by fnarf1** [wowsims/tbc#641]
**Describe the bug**
Whenever I select 'Twist Fire Nova' I get an error and am unable to to sim my DPS. Works perfectly fine as soon as I unselect the Fire Nova twist option.

**To Reproduce**
1. Go to the 'Settings' tab
2. Click on 'Twist Fire Nova'
3. Click on the 'DPS' button

**Expected behavior**
I expected the sim to work despite having 'Twist Fire Nova' selected.

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/103289294/162536735-f922443c-05de-4f1c-b491-00c52bde1a97.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version 100.0.4896.75 (Official Build) (64-bit)

**Comment by WaDaFruCK** [comment]
You may want to provide an export on this one, as my twist fire nova setting works fine.

**Comment by jimmyt857** [comment]
Thanks, was able to reproduce and this should be fixed now.
