### ISSUE TITLE
Missing items: [Drums of War]

### ISSUE THREAD

**Issue by WaDaFruCK** [wowsims/tbc#645]
[Links to [TBC Wowhead](https://tbc.wowhead.com/items "https://tbc.wowhead.com/items") for each item:
](https://tbc.wowhead.com/item=185852/greater-drums-of-war)

**Comment by jimmyt857** [comment]
This has been added now. It's only available in the Consumes section and not in the Buffs section because this item shouldn't ever be used and it's not worth taking up permanent screen space on Settings.
