### ISSUE TITLE
Arcane Mage JSON Import Error

### ISSUE THREAD

**Issue by haydenrice** [wowsims/tbc#664]
**Describe the bug**
When importing JSON data that was exported from the website to the locally hosted windows executable for Arcane Mage, I am getting the following error message: "Import error: Error: Found unknown field while reading proto.MageTalents from JSON format. JSON key: magicAbsorption". 

**To Reproduce**
1. Go to 'https://wowsims.github.io/tbc/mage/'
2. Click on 'P2 Arcane Preset'
3. Click on 'Export -> JSON'
4. Download the file or copy the JSON string to clipboard
5.  In the locally hosted simulator, click 'Import'
6. Paste the JSON data in the clipboard into the textbox, or upload the file previously downloaded from the website
7. See error

**Expected behavior**
To be able to export my character info from the web version and import it into the local version.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 10.0.19043 Build 19043
 - Browser: Mozilla Firefox 99.0.1 (64-bit)
 - Version [e.g. 22] wowsim v1.7.1

**Smartphone (please complete the following information):**

**Additional context**
I originally got the error message while simulating my custom gear set, but I was able to replicate the error message using any of the phase preset gear options as well during my troubleshooting.

When exporting from the web version and then importing the data back to the web version, I do not get the error.
When exporting from the local version and then importing back into the local version, I do not get the error.

Looks like you may have a discrepancy between the web and desktop versions of the program and how they handle the imported JSON string.

I hope this helps! Good luck and good work!

**Comment by jimmyt857** [comment]
Ahh, this is probably due to an out of date downloadable binary. @lologarithm could you update it?

**Comment by lologarithm** [comment]
https://github.com/wowsims/tbc/releases/tag/v1.7.2 doesnt crash for me doing an export->import.  @haydenrice let me know if the newest version fixes the issue for you.

**Comment by haydenrice** [comment]
@lologarithm That seems to have done the trick. I can no longer replicate the issue. Thank you for the speedy response and resolution!
