### ISSUE TITLE
Import raid from WCL

### ISSUE THREAD

**Issue by lologarithm** [wowsims/tbc#702]
rough example here: https://pastebin.com/JyXSK8S7

this will allow an entire raid to be populated instead of requiring manual inputting

We should be able to pull items, enchants, gems, weapon oils/imbues.  
buffs:
1. Include all raid buffs correctly (especially paladin buffs) Checking for existing is probably enough ( no need to simulate exact uptime for like arcane int because it might have fallen off)
2. Temp buff targets should be able to be extracted (PI, Innervate, etc)

**Comment by Bengejd** [comment]
So I have a basic version of this that I'm [working on](https://pastebin.com/GtsmsjGj) in Google Sheets. It's far from complete, and really rough around the edges. I've only tested it on myself in one raid log, so it'll at least output the correct Player Details for BM Hunters.

Note: This will not give you the correct setup for importing directly into the raid. I was doing it via exporting an empty raid, and changing one of the empty player objects into the object that was `console.logged` out.

# Road Blocks:

### Talents
WCL cannot provide (or does not provide) specific talent choices. The best I've been able to find over the last few years is the standard `41/20/0` format for talents. So these would have to run under the assumption of standard spec talents.

### Enchants
WCL provides enchants in the form of the actual ID of the enchant, whereas WoW Sim uses the Spell ID to identify enchants.

E.g: Glyph of Ferocity
WoW Sim ID: [29192](https://tbc.wowhead.com/item=29192/glyph-of-ferocity) - `item URL ID`
WCL ID: [3003](https://tbc.wowhead.com/spell=35452/glyph-of-ferocity) - `Enchant Item: +34 Attack Power and +16 Hit Rating (3003).
`
### Consumes
WCL provides consumables in the form of the buff ID, whereas WoWSIM uses a `TypeNAME` format
e.g: `WeaponImbueAdamantiteSharpeningStone`

## Unimplemented / Untested in my Pastebin:

- All specs / classes besides BM Hunters (some frameworks in place).
- Weapon Enhancements (Oils, Stones, etc...)
- Parties (Probably impossible to do reliably?)
- Consumables from the log (Stated above)
- PI, Innervate, other temp buffs
- Enchants (Stated above)
- Encounter Settings
- Paladin Buffs
- Tanks

**Comment by Bengejd** [comment]
@lologarithm I must have completely missed the experimental flag in the raid sim, so that's good to hear that it's mostly implemented! 

As for party makeup, yeah it's not going to be 100% reliable, but using the auras that I listed above, I was able to get the DPS groups almost perfect, with very little moving around required. It obviously requires a bit of finessing on which auras are going to be reliable, but this was what I found to be the best indication.

I used WCL's V2 GraphQL API in my version, which used the following query:

```
 let query = `{
          reportData {
            report(code: "${reportID}") {
              table(dataType: Buffs, startTime: ${startTime}, endTime: ${endTime}, sourceID: ${this.id}, viewBy: Target, abilityID: ${buffId}, hostilityType: Friendlies)
            }
          }
        }`
```

And only ran it on `Warriors`, `Paladins`, and `Druids` (for the time being).

**Comment by Bengejd** [comment]
So for example using Leader of the Pack, you'd end up with a query that would look like:

```
{
  reportData {
    report(code: "rbYpNZVMcxykjFd3") {
      table(dataType: Buffs, startTime: 668627, endTime: 749429, sourceID: 44, viewBy: Target, abilityID: 24932, hostilityType: Friendlies)
    }
  }
}
```

And would result in a list of the players who had that aura from `sourceID: 44`, which would be:

![image](https://user-images.githubusercontent.com/11723093/172273646-e5e82d03-52e9-48ef-9e7f-cd9c9dc10f63.png).

Then you can just link those players together in a group, add them to a party, and continue on your way. Filtering out Player pets is also required, but that's the general idea that I was utilizing.

**Comment by lologarithm** [comment]
Here is my query so far
```
{"query":"{reportData { report(code: \\"${reportID}\\") { guild { name faction {id} } playerDetails(fightIDs: [${fightID}], endTime: 99999999)  events(fightIDs: [${fightID}], dataType:CombatantInfo, endTime: 99999999) {data}  fights(fightIDs: [${fightID}]) { startTime endTime } buffs: events(fightIDs: [${fightID}], dataType:Buffs, endTime: 99999999, abilityID: 29166){ data }}}}"}```

I pull out combatant info + player details to get names and specs. I then match the spec (X/Y/Z) to the closest spec we have pre-built. 

I pull buff data right now just to see who cast innervate (to setup innervate targets).  Paladin buffs for now are just using our sim defaults (each class has a priority order)

There are a few small things missing/broken 

- Party Makeup
- Sometimes import will result in a blank player. Importing same log again will fix the issue.
- We have since implemented prot paladin / feral and so I need to change those from being buff bots to being fully implemented tanks
- Pulling consume usage to select consumes for each player

**Comment by Bengejd** [comment]
I'll reach out to you on Discord with some of my thoughts, I have some of this information readily available in my Google sheet, unrelated to the WowSim stuff.

**Comment by lologarithm** [comment]
Going to close this issue as we now have it working and released. We can create new issues if we want to track specific features to be added.
