### ISSUE TITLE
protection warrior dps / tps

### ISSUE THREAD

**Issue by philipbaum** [wowsims/tbc#724]
**Is your feature request related to a problem? Please describe.**
the sim is currently not using devestate and shield slam. Maybe you only want arms / fury using the sim.

**Describe the solution you'd like**
have all abilities be simulation able

**Comment by jimmyt857** [comment]
Prot warriors are going to have their own separate sim, which we're working on!

**Comment by philipbaum** [comment]
Thanks for the swift reply. Keep up your great work!
