### ISSUE TITLE
Warrior Simulator attempting to refresh a snapshotted Battle Shout.

### ISSUE THREAD

**Issue by JoeyWButler** [wowsims/tbc#729]
**Describe the bug**
The simulator attempts to refresh precasted snapshot Battle Shouts prior to fading. 

**To Reproduce**
1. Go to "SETTINGS"
2. Check "Precast Shout", and either "Precast with Sapphire", or "Precast with T2"
3. Ping DPS to simulate.
4. Go to "LOG" and search for Battle Shout.

**Expected behavior**
Precasted snapshot Battle Shouts cannot be refreshed before fading, unless the aura is canceled. The logs correctly reflect this behavior, and the attempt fails to refresh the Battleshout, however it is still a wasted GCD.

**Sim Links and Screenshots**
[[If applicable, add links to your sim settings or screenshots to help explain your problem.]]
Screenshots of Logs and Timelines:
(https://imgur.com/a/rrlylTf)

Exported Simulator:
https://wowsims.github.io/tbc/warrior/#eJztUk1rU0EUzbkvL06GKtPYyhhQ6ltIFIT3GgItCB13dvekIF1JFRSFbtpVdJXaBFNXRRetdqHFPxBcyEOhlBZsoR924SLFb6kuLFhaEBexjTNvyD9w6Z3hnjvn3Ll3ZhhOOcpIhhowDXoKyqFIJTgR3HlQdip1F6lw+Ort66PskEhn58CFWNuHrG7BSz3ax9cGeFK8OTD8+B5k/Yvm1xoxz8RqheTbCeJHRXMXcvEVvLTW7NTy3AFkY9NE7/5ArujENrHxwxYwGYfFmC756Ts8x9QT4vU4yd/vdcLKB2zGnX9tGV+vkPZL30z8bMcUnPoIOVMmHc3qzk9qRlmokHeiRskSuVXCMiU/k1snt+jUQZMOph2c3aDEf/undocxKEjqwegAPy9QxBkr9KvABr2qN8bSZXXBMh2qP8b5ayrETQxhEJNAJpFtT7cyJbqQg4/78PIF3y8EfpD3u/3gnF/QQxMGgm7jgsJjhFzwI2ziWFezZeAud1h5iKd4ks3eI4PxDzL44rnFskXWiDrj9cOXdluzwwvtURJX1KnWoY9HJyvbl6L1vkzeij2RkpQ5LfQDVIEScJFCGtT3KeLWjdh+9o3Ymz5QfwEK35BV

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox

**Additional context**

**Comment by jimmyt857** [comment]
Thanks for reporting, I think this should be fixed now.
