### ISSUE TITLE
I'd like to request an annihilator debuff, singular, double or triple proc. Then I could properly gear around that armor pen

### ISSUE THREAD

**Issue by flebbis** [wowsims/tbc#741]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jimmyt857** [comment]
Simulating the stacks going up over time is something we'd normally do in the raid sim. If you just want a static buff, would the Bonus Stats (in the Gear tab) accomplish what you want?

**Comment by jimmyt857** [comment]
Closing since OP hasn't responded and this is doable in the sim already using Bonus Stats.
