### ISSUE TITLE
[Bug] Missed ability hits are refunding rage

### ISSUE THREAD

**Issue by TheGroxEmpire** [wowsims/tbc#747]
**Describe the bug**
Missed ability hits are refunding rage by 80% of ability rage cost.

**To Reproduce**
1. Load any config without yellow hit cap
2. Observe missing yellow hit (ability) on timeline view

**Expected behavior**
Missed ability should not refund any rage. Rage refunds for ability should only happen for dodge or parry ability hits.

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/47816228/164966992-48412b48-d809-4ce3-ba89-605ca69956e0.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Google Chrome
- Version 100.0.4896.127

**Comment by vigo2** [comment]
This is the correct behaviour. Refunds work on misses as well.

**Comment by TheGroxEmpire** [comment]
> This is the correct behaviour. Refunds work on misses as well.

I doubled checked and you're correct. Thanks for reminding me Vigo.
