### ISSUE TITLE
[Bug] Slam are sometimes not being casted after an auto

### ISSUE THREAD

**Issue by TheGroxEmpire** [wowsims/tbc#748]
**Describe the bug**
Slam are sometimes not being casted casted after an auto,

**To Reproduce**
1. Load slam warrior config
2. Observe slam rotation in timeline view

**Expected behavior**
After an auto attack (white hit or queued ability auto), slam should always be casted unless the swing timer is below the threshold option (Slam swing timer threshold option is not yet on the sim).

**Sim Links and Screenshots**
<details>

<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/47816228/164968088-0cc60b8d-63d3-465c-bb37-561b0eb9fdac.png)
</details>

<details>

<summary>Sim link</summary>

https://wowsims.github.io/tbc/warrior/#eJztUjGLE0EUzvc2CbMD6rieuqaKi0oUhNldAlrIjdhoI0FEjhPkFBQVC++qaBWCRWISCWJxCmphYXtYxIDNBYsIIggK3oHiCWIjCNqcsMr5djcRf8CVvmLmve/73se8x0gqkVMUWADNg0owqFIN1k+gj9wiqAtaAQrDfB35ypWz187PiZyyC68glbrfJrfxGV7+a53u/oa0Va9NnrVaJyaXmPz1lMlBhDcR5AY1aJH7tsmCZS63qA8seP4Mns0sI4NE0+yQGy3Ds+JSqcesecktsUncZasfnb8Gbfb7+IUNBkn3yOAWuavvkWqyqtMiPofd+HzwKUaiNkmhet/hPlyAzDByp0VeoU9UIzQILyi7QrklylWtroV5C/teU+Z/rGtcF4I/mksHMDctjwgouMm3w96UP278NNllDib34glzOEUmzLEUOWcquIgZTKELOJnCZjsVnDQuiihB4yZ2h4HWYaj9sBxoX5e1DgJ/vy5zouOqHPiBDu/hstwkLXFjxhGJRe2UkQW5UTS3FdfGgRHH/lLJrIj6W/9RM6J6T8YaM23kdjZcm3DUeI5Uetp4ldE7z5id44l2yHePrh6Sw0knTEm/b1xy9iheUgPgvRxFhaZ42CpdupDEt8nZdA23zR83rZKQ
</details>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 100.0.4896.127

**Comment by jimmyt857** [comment]
#753 mitigates the issue but I don't think its completely resolved. Getting this right seems really tricky.
