### ISSUE TITLE
Shaman - Elemental Precision is not being applied to Flametongue attack

### ISSUE THREAD

**Issue by Jazz405** [wowsims/tbc#779]
Elemental Precision adds 2% hit (per rank) for fire/frost/nature spells done by the shaman. When selected, the extra hit is being applied to nature/flame/frost shock but is not for flametongue attack. Unless I'm mistaken, 
https://tbc.wowhead.com/spell=30673/elemental-precision#modifies;name=flame says that it should be applied to the flametongue attacks,

Additionally, the same behavior (as above) applies to Lightning Capacitor. In the sense that Lightning Cap is not benefiting from the Nature +hit

1. Select Flametongue Weapon as your imbues
2. Do not spec into Elemental Precision
3. Run a sim, see Miss% for flametongue attack, shocks, etc
4. Spec into Elemental Precision
5. Run sim, see that Miss% for shocks is updated but not flametongue attack

**Expected behavior**
Flametongue (and Lightning Cap) should be benefitting from the additional Hit from Elemental Precision talent

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 101

**Additional context**
Admittedly a Niche spec, but this tool is the best tool to research and play with Spellhance builds

**Comment by jimmyt857** [comment]
Thanks for pointing this out! Should be fixed now.

Lightning Capacitor does NOT benefit from this talent, so the sim is correct there. As an ele shaman this is an interaction we care about a lot.   :)
