### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by menders** [wowsims/tbc#781]
Unable to run sims using Safari on macOS 12.3.1.

**Comment by jimmyt857** [comment]
We'll need a bit more information on this. What does, 'unable to run sims' mean? Could you include screenshots and/or a link to your settings?

**Comment by menders** [comment]
![Screen Shot 2022-05-13 at 5 42 03 PM](https://user-images.githubusercontent.com/3136222/168404380-243fc699-8b2d-4307-bff0-2b28d337b75c.png)
![Screen Shot 2022-05-13 at 5 42 18 PM](https://user-images.githubusercontent.com/3136222/168404386-2af7372a-e867-4770-a974-a2d8495f52db.png)
![Screen Shot 2022-05-13 at 5 42 28 PM](https://user-images.githubusercontent.com/3136222/168404388-60169fe8-dd8e-4748-9c53-39ea580806d1.png)

I cannot run the sim with any settings. Clicking on the DPS button results in nothing.

**Comment by jimmyt857** [comment]
Hmm ok, we'll try to figure something out. The hard part will be finding a developer on this project with a Mac   xD
