### ISSUE TITLE
EP

### ISSUE THREAD

**Issue by klinokAS** [wowsims/tbc#787]
**Describe the bug**
ep stats over buttons

**To Reproduce**
1. Go to 'https://wowsims.github.io/tbc/warrior/'
2. Click on 'EP WEIGHTS'
3. w8 for sims
4. and stats weights over buttons https://prnt.sc/uXoiqOLwSKzZ (screenshot)

**Expected behavior**
idk, think smthng like this https://prnt.sc/9rWRoarCRxF3

**Desktop (please complete the following information):**
 - OS: win10x64
 - Browser opera gx LVL3 (core: 84.0.4316.52)
 - Version 84.0.4316.52

**Additional context**
on 80% window size scale it's working ok https://prnt.sc/9rWRoarCRxF3

**Comment by jimmyt857** [comment]
This is now resolved, because the UI for EP has been moved to its own menu.
