### ISSUE TITLE
Deathfrost Enchant

### ISSUE THREAD

**Issue by WaDaFruCK** [wowsims/tbc#788]
https://web.archive.org/web/20120210154356/http://elitistjerks.com/f15/t27347-deathfrost_its_mechanics/p4/

Based on that thread, and corroborating evidence, it appears the spellcast proc version is a 50% chance to proc, with a 25 second ICD, while the melee proc version is about a 2.15 PPM. Both effects can fire on the same character independently of each other, and once per weapon enchant; IE you could get 4 procs at the exact same time off of a melee with flametongue if you were very lucky.

Procs for 150 damage, scaling off of frost damage effects (not spellpower) and spell hit/spell crit, effected by talents that increase crit intensity such as meta gem and boss debuffs but not spell damage.

Should mark as phase 5 as it will be available in June.

**Comment by jimmyt857** [comment]
I'm pretty sure this recipe is already available from the holiday last year.

Implementing this will be pretty low-prio though, as I don't think anyone uses it.

**Comment by WaDaFruCK** [comment]
It actually never dropped the prior year, even though it should have; Most likely due to the offset of time of year of original TBC to TBC classic.

I'm interested in how it sims specifically with enhance, and I've seen a few discussions that it may be useful for ret paladins; basically any class that can double-dip on using both the physical and the spell proc of it. Definitely low prio though.
