### ISSUE TITLE
Multiple lusts simulation TBC Hunter Sim

### ISSUE THREAD

**Issue by hazzal** [wowsims/tbc#799]
**Describe the bug**
Multiple bloodlusts doesn't happen in windows executable version of simulater even if selected in settings. I tried to reproduce in the online sim at https://wowsims.github.io/tbc/hunter but there both lusts correctly appear to be cast if I select 2

**To Reproduce**
1. Download latest windows version of sim
2. Open hunter sim and select 2 lusts in settings
3. Look at timeline, combatlog etc to see that only 1 lust gets cast even when 2 were selected on a 180 second sim.

**Expected behavior**
Every bloodlust selected in the settings should be cast, not just one. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox 99.0.1 (64-bit)
 - Reported version of sim in command promt: 1.7.3

**Additional context**
Will try on different computer(s) later and report if same issue happens there.

**Comment by jimmyt857** [comment]
This was a bug which was fixed a week or two ago. I think it should be included in the most recent version of the executable, if you download it again it should work!

**Comment by jimmyt857** [comment]
Marking closed since OP hasn't responded and this issue is not reproducible.

**Comment by hazzal** [comment]
After some testing it worked correctly in version 1.7 of the program. The issue seemed to be isolated to version 1.7.3 that I had downloaded (doesn't seem to be available for download any more). And multiple lusts works correctly again in version 1.8 so this issue appears to be solved.
