### ISSUE TITLE
[Bug] Weapon stones in OH affects 2H weapons dps result

### ISSUE THREAD

**Issue by TheGroxEmpire** [wowsims/tbc#812]
**Describe the bug**
There's a noticeable dps difference when enabling weapon stones in off hand slot while using 2H weapon.

**To Reproduce**
1. Load the linked config
2. Observe the dps result, set it as reference
3. Enable adamantite sharpening stones in OH
4. Observe the dps difference

**Expected behavior**
Weapon stones in OH should not affect 2H result at all.

**Sim Links and Screenshots**
https://wowsims.github.io/tbc/warrior/#eJzjYtJgEhLmYK1gamBk3sHIeoCRaQIj0wNGRqkbrE2MbAE5iZWpRRysApxSuxm5BAS+/mGU6HjCqMQ28y/jL6AIi0DLH0YuDoFJHxklbjxk5OIVOLyXUeJKJ5MSM0haWOA/UOLwbkYlzrO/GSEIqKYfKPj7JqMSM4grIDANaOhpoBY2oBaQLh6BWa+BVjz6zQhEQMOvAuXvPwOpvAlkfb8DlIMaxSKw9hWIPP8HRP7uYQKS8x6C9Lx5wygxu4WJiwEocuwPoxLfBiaWE0wsD5hYbzCxVjBrXWBiGAVUBVUcHIwOjBJMFoxF3lyOAowSjBWMDYyMmhBZPwdDCEPFwRJMHwhycISIiDh4QkSSHAIYMxgTGCMYJzAyCjFIsQgwKjB2MaoaGxkYGBsbGBqbGhkYGpgaGBgZGeoamAIZBiCeqZGhkYHxLEYNLjZgZG/bBEwoXHwcnWIK/2GAkYuVi5mjJQFMbedV8uIEW+iQ6qAIc4LkrJkgcNJeSBciybLPQcFTSEEA6CcPpgCmCKC7Kpgy08DgnX0hxMWTHABwO4NS

**Desktop (please complete the following information):**
 - OS: Windows 10
- Browser Google Chrome
- Version 100.0.4896.127

**Comment by jimmyt857** [comment]
Fixed in https://github.com/wowsims/tbc/commit/a42d7f20c28922ba13526d68e5e7faafec23c993
