### ISSUE TITLE
[Bug] Sword Spec is still not converting into heroic strike

### ISSUE THREAD

**Issue by TheGroxEmpire** [wowsims/tbc#826]
**Describe the bug**
Sword spec that is procced from off-hand / abilities while main-hand is queueing heroic strike should be converted into a heroic strike. This bug was said to be fixed in #749.

**To Reproduce**
1. Load a setting with sword spec talent and equipping swords on both slot
2. Simulate
3. Observe sword specs proc that are happening during heroic strike queue that are not procced by main hand hits

**Expected behavior**
The sword spec in the screenshot below should be converting into heroic strike.

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/47816228/166671886-a492ac22-4e30-4314-94c5-5e72bb469ebd.png)

**Additional context**
[Original test of the observed behavior.](https://github.com/magey/tbc-warrior/issues/5#issuecomment-861021814)

**Comment by TheGroxEmpire** [comment]
I didn't save the original seed but I was able to reproduce it. 

It happens in 151s of the fight. Basically what is happening is that the sim has enough rage to queue heroic strike (60 rage at 60 threshold), the sim casts WW (-25 rage into 35 rage) and the WW proc sword spec while the HS are dequeued at the same time. This kind of dequeue should not be possible in-game even with perfect play at virtually no delay.

Would it be possible to add miniscule delay to dequeue just to stop this from happening?
<Details>

<summary> Sim link and seed</summary>

Sim was run in one iteration through the button on timeline view.
RNG Seed: 364905277
https://wowsims.github.io/tbc/warrior/#eJztjk8rRFEYxuc5c0d3Lup0WVyzGpcFSt070y1Wcyyn0GQhSxRRNqyG1Q2LGRuycmdh8g1mqZTURKSJBWVKiWSjFBvJFecP+QKW3sU5z/t7zvu8xyBdxDR1bIF0IU98RHcROwBJ7MeW0ZCbm1icWtBjNJ6owqA0fIZVuIfdEHyg9g5Do6uh4CsvsK5uOefwjnOdVkNYF0VitNBPPlPdgx2vS0/YzXSdw/c67GhNtm+8PS0SO8rfGE209KiiajLqkkfdPIg1da5er389jT5/iPMsFOeb1Nu3YubQJ1a5ItTRt9JowFMbK0QrEBwTLR/tOSeR//rTWtJ1MFikDwujxmC3gsPMVaKT9cv7YIQNKNLKsopMsgAKLbIdpViZ5TCDcYxhAzAjCc1CEmvoSHuO4zmum3ZSjut4vbzhxPHE5aakVULEHorLGH+atf8saysFok4ypqNMbZ8lsxYx2yn/tg/kyBhfmCez07KeMvPqe5vsC91ieds=
</Details>

**Comment by jimmyt857** [comment]
Ah the actual bug is slightly different; for HS casts on bonus attacks we're still dequeuing HS and checking if the rage threshold is met (https://github.com/wowsims/tbc/blob/master/sim/warrior/heroic_strike_cleave.go#L115). This should be a pretty simple check I can add later.

To confirm, do Heroic Strikes from bonus attacks cause HS to be dequeued? Also, do they cost rage? If they are free, do they still go through if rage has fallen below the HS cost?

**Comment by TheGroxEmpire** [comment]
> To confirm, do Heroic Strikes from bonus attacks cause HS to be dequeued? Also, do they cost rage? If they are free, do they still go through if rage has fallen below the HS cost?

It acts like normal HS; gives HS bonus damage, dequeued after cast, costs rage.

**Comment by TheGroxEmpire** [comment]
Unfortunately it is not fixed yet still. With the same setting above and this seed: 2145684556.
![image](https://user-images.githubusercontent.com/47816228/167005163-9232b9ed-2df9-4ed9-86fc-47e15a18b3cf.png)
