### ISSUE TITLE
spell hit not counted into EP

### ISSUE THREAD

**Issue by devinciownz** [wowsims/tbc#839]
spell hit not counted into EP or DPS  numbers when i open the list of gear on my balance druid sim. i tried hit capped and not from gear. i tried to remove spell hit talent. using preset gear/talent/settings tabs and customized, changing the spell hit value in the EP list of settings (top right corner cogwhell) . even remove cookies. spell hit count as 0 in the total ep of items no matter what i try. EX: [Shadowcaster's Drape] https://tbc.wowhead.com/item=33591 give 75 dps and [Ruby Drape of the Mysticant] https://tbc.wowhead.com/item=28766 give 47 with haste value of 1.2 and spell hit of 2.4

**Comment by jimmyt857** [comment]
The values shown in the item selector menu are EP values, not DPS values (and the column is titled, "EP"). They are approximations of DPS and should not be used to determine what's actually best for you; it's just a quick reference to sort the items in a reasonable order.

We've had a lot of issues with spell hit EP screwing with the item order in inconvenient ways, so its actually disabled; regardless of the EP value you put for spell hit it won't get used in the sorting. In the future maybe we can provide a toggle for this in the options menu or something, but it helps more often than hurts. Sorry in your case it hurt  :(
