### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by respect722** [wowsims/tbc#909]
Links to [TBC Wowhead](https://tbc.wowhead.com/items "https://tbc.wowhead.com/items") for each item:
hey thanks for your great calc
i think you need to add flame cap on 
https://tbc.wowhead.com/item=22788/flame-cap

**Comment by jimmyt857** [comment]
I'm not sure which sim you're looking at, but most of them already have Flame Cap. It's in Settings --> Consumes, in the 2nd box on the 1st row.

**Comment by respect722** [comment]
Imagine as fire mage you want start with flame cap + destruction pot and
continue with mana gem an mana pot
There is option that you choose starting potion but it would be nice if you
add starting with destruction + flame cap

**Comment by jimmyt857** [comment]
Ah, gotcha. Will update this today!
