### ISSUE TITLE
Shattered Sun Pendant of Might Buff not being simmed.

### ISSUE THREAD

**Issue by Ikerstreamer** [wowsims/tbc#931]
[https://tbc.wowhead.com/item=34679/shattered-sun-pendant-of-might](url)

It seems to be that the buff granted by Shattered Sun Pendant of Might is not properly being accounted for in the sims. It doesn't appear anywhere on the timeline nor on the buff list provided in the application.

**Comment by Ikerstreamer** [comment]
I realised now that this is only the case in the latest release and has been fixed in the live version of the code.

**Comment by jimmyt857** [comment]
Glad this is mostly resolved; a new binary will probably go out fairly soon when we release the next sim.
