### ISSUE TITLE
Customize Debuff uptimes

### ISSUE THREAD

**Issue by Bengejd** [wowsims/tbc#933]
**Is your feature request related to a problem? Please describe.**
Currently, a majority of the boss debuffs are set to have a 100% up time, which isn't accurate to a real raid scenario.

![image](https://user-images.githubusercontent.com/11723093/170084986-37764862-a366-431b-b447-4d3854604f54.png)

**Describe the solution you'd like**
It would be nice if we could customize the up time on these debuffs, in a similar manner to the Expose Weakness uptime, probably in it's own tab or section.

![image](https://user-images.githubusercontent.com/11723093/170085219-d0ace9cb-3b00-4515-8531-ced143e85eb5.png)

**Describe alternatives you've considered**
There is no real alternative to this.

**Additional context**
This would allow the sim to be more accurate in a real raid scenario, I like to go back through logs and check to see if I was doing as much DPS as I could be doing, given my gear & debuff uptimes on the boss.

**Comment by jimmyt857** [comment]
Thanks for the report Bengejd!

Unfortunately, this is something we've discussed and intentionally decided to keep out of the sim. There are a lot of factors here, but the main ones are these:

- We do not model fight mechanics, so every sim represents a Patchwerk-style encounter. If you look at logs of encounters like this (e.g. Teron Gorefiend) you'll find that real raid scenarios do have ~98-100% uptime for all of these buffs. The missing 1-2% usually represents the time spent moving into position, where the player is not yet doing damage anyway. So in terms of 'effective combat time' they are ~100%.
- Sims are complicated tools, and most of the questions we get from users already involve mistakes like forgetting to set an option or misunderstanding how something works. Adding another 10-15 options representing uptime for each debuff would use a lot of screen space (making the whole site less user-friendly) and more complication (so users would make even more mistakes).
- Adding the options you're suggesting here still won't be enough to achieve your stated goal. If your goal is to understand EXACTLY how much DPS you should be doing, then we would need to add hundreds more options. Even just regarding buff uptime, WHEN the buff is active matters in addition to the uptime %. For example, if a buff has 98% uptime and the missing 2% occurs during your cooldowns, it will be different than if it comes after your cooldowns are over.

**Comment by Bengejd** [comment]
I appreciate the insight into why this won't be implemented. Although, I still somewhat disagree with some of the points, I can respect the stance, and appreciate the detailed response none the less.
