### ISSUE TITLE
Customize Player Active Time

### ISSUE THREAD

**Issue by Bengejd** [wowsims/tbc#934]
**Is your feature request related to a problem? Please describe.**
It's unrealistic to simulate a player having a 100% up time on a boss, so having a custom setting to allow us to set our uptimes would be beneficial. High 98%'s are typically what you'd expect to see on a tank & spank boss.

**Describe the solution you'd like**
Allow us to customize our uptime, similar to the Expose Weakness Uptime %.
![image](https://user-images.githubusercontent.com/11723093/170086676-db432a4b-bf19-400d-9f0e-8a1fbe4c1408.png)

**Describe alternatives you've considered**
Increasing latency "works" but isn't representative of what you'd actually be seeing in a real raid setting.

**Comment by jimmyt857** [comment]
Thanks again for the reports; the answer here is similar to your other report (#933). TLDR, we don't simulate non-Patchwerk fights, it's not clear what an option like this would represent, and it would increase UI complexity without adding clear value.
