### ISSUE TITLE
Weapon Speed and Weapon Damage Stat Weight Options

### ISSUE THREAD

**Issue by Djurkwhad** [wowsims/tbc#936]
Looking for an option to input stat weights for Weapon Speeds, and Weapon Damage

**Comment by jimmyt857** [comment]
Stat weight doesn't make sense for weapon speed because it's a highly non-linear stat. Weapon damage is something we could do, although it's unlikely we'll have time for it before we need to start writing the wrath sims.

**Comment by jimmyt857** [comment]
Closing because we won't have time to consider any version of this with wrath coming soon.
