### ISSUE TITLE
Unable to Load the SIM (.exe)

### ISSUE THREAD

**Issue by 01Lanz** [wowsims/tbc#944]
**Describe the bug**
Can't load the SIM
```
index.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
DevTools failed to load source map: Could not load content for https://unpkg.com/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://unpkg.com/@popperjs/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE**
```

**To Reproduce**
1. Run the EXE file.
2. The class selection appears
3. Getting blank screen after clicking on the desired class

**Expected behavior**
The character sheet to load normally.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Opera GX LVL3 (core: 86.0.4363.64)

**Additional context**
The online SIM works just fine, however, I can't get the EXE file to load as it used to.
I've tried to disable all security measures, Anti-Virus / Firewall, tried to clear all Cache/Cookies, but the problem persists.

**Comment by lologarithm** [comment]
try a different browser and see what happens. I don't have opera installed and its such a tiny part of our userbase.... I will try to find some time to see if I can figure this out.

Let me know if swapping browsers works for you.

**Comment by lologarithm** [comment]
Just found a bug report in Go that it respects a particular erroneous windows registry setting that causes js files to be served as text/plain instead of text/javascript.  It looks like I can hand fix this for now until next version of Go fixes this.

**Comment by 01Lanz** [comment]
It loaded just fine with the 1.9 version, thank you!
