### ISSUE TITLE
Elemantal shaman talent Call of thunder 

### ISSUE THREAD

**Issue by Kakan44** [wowsims/tbc#948]
**Describe the bug**
The crit chance from Call of thunder is only applied to Chain lightning

**To Reproduce**
1. Run any sim with elemental shaman with talent CAll of thunder picked
2. open detailed result to view the damage from each spell
3. notice that chain lightning somehow has 5% more crits made than lightning bolt

**Expected behavior**
Call of thunder gives 5% crit at 5/5 points to both chain lightning and lightning bolt

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/6643359/170844038-897abc86-d847-44a3-9ec5-7331d7818ce2.png)

**Desktop (please complete the following information):**
chrome
Version 101.0.4951.67

**Comment by jimmyt857** [comment]
Call of Thunder is definitely included in LB. The usual reason for CL having higher crit is because of the Elemental Mastery CD.

If you're sure it's not because of the CD, then link your settings.

**Comment by jimmyt857** [comment]
Ok sounds good! Going to close this for now, feel free to reopen if you find something conclusive.
