### ISSUE TITLE
Mainhand 1h de-selection causes other slots' item lists to disappear

### ISSUE THREAD

**Issue by pdwilcox** [wowsims/tbc#973]
**Describe the bug**
In Elemental shaman simulator: when unselecting "1H" in the main hand weapon menu: all other slots' lists become empty.   (is this a default checkbox that is used in a hidden way in all other selections?)

**To Reproduce**
1. Click on Main hand
2. Uncheck 1h
3. close Main hand window
4. Open other slots

**Expected behavior**
I did not expect the selections from one menu to effect the others.

**Sim Links and Screenshots**
my arrangement:
https://wowsims.github.io/tbc/elemental_shaman/#eJzjYuNgVGDSYHJi4WCUYBRikPrP0sTIFpCTWJlaxMEkwC51lJFLQGDZJ0aJ9ieMSmxrupmu/2bkYhHY/wokvh4ofu0hUBwoeAsoziFw+g+jxL8mJi5hgZVAucO7GZU4j/xmhCCg9Kl/jBJtGxi5eAUWAKU/3GFUYr4FNm/KH0agniMfGSUu7UXRIyDwAGjkw8lMSmxwU/qBpnRsQGaxCOx6CiI/PgCJvv3NKDEbLLqthQlInvrDqMS3gYmxgYn5BBNjBdMMRkatC0wMo4CqoAqYlBwYBZiSxLh4pDiAiYdFglmBkQOUqICJS4Cxi1HR1NTAwNjQwNTQwMDI0NjYFMTU1QXxTY0NgIKmsxgZlLqZOcHmNaQ5KEJMFnGQnDUTBE7aC71lUvCUYBq00VfiQBVjmPcRMMebOvYgAUsw2XHYwREq4BDBmMAIAIy0afw=

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 101.0.4951.67     (wtf, version 101...)

**Additional context**

**Comment by jimmyt857** [comment]
Thanks for the report! This should be a simple fix.
