### ISSUE TITLE
Add Kil'jaedan haste buff to warrior sim

### ISSUE THREAD

**Issue by cmith44** [wowsims/tbc#977]
During the Kil'jaedan fight, warriors have a high uptime on the haste buff from dragon (https://tbc.wowhead.com/spell=49725/breath-haste). It would be cool if this could be taken into account for the warrior sim. For example, it could be added in the cooldowns section (along with death wish, haste potions etc).

**Comment by WaDaFruCK** [comment]
As far as I know, Lust does not stack with the haste buff for melee attack speed; so you could "rig" it by just giving yourself extra lusts/higher lust uptime, manually setting up the lusts to time with when you expect 85%+30 seconds would be etc.

**Comment by CalebinoPepito** [comment]
> As far as I know, Lust does not stack with the haste buff for melee attack speed; so you could "rig" it by just giving yourself extra lusts/higher lust uptime, manually setting up the lusts to time with when you expect 85%+30 seconds would be etc.

Lust and the dragon haste buff do indeed not stack, and the solution you propose is what I have been doing so far. It's a decent workaround, however the 2 buffs aren't exactly the same: the dragon buff provides +25% haste for 30s whereas bloodlust provides 30% haste for 40s. So simply using extra lusts doesn't accurately reflect how the fight would be. An another issue is that the sim currently caps the number of Bloodlusts one can give oneself at 10, meaning one could only "rig" it for 400s = 6mins40s (assuming one does not actually get 1 or more bloodlusts), and this fight can be longer than that for some players.

**Comment by jimmyt857** [comment]
Migrating to wrath in the next week so this won't be fixed.
