### ISSUE TITLE
Missing items: Fetish of The Fallen

### ISSUE THREAD

**Issue by Scubrah** [wowsims/tbc#996]
Links to [TBC Wowhead](https://tbc.wowhead.com/items "https://tbc.wowhead.com/items") for each item:
[Fetish of the Fallen](https://tbc.wowhead.com/item=27416/fetish-of-the-fallen)

**Comment by jimmyt857** [comment]
This item is below the cutoff we use (has item level 100, we only show >= 105 for blue items). I don't think we want to lower the cutoff, but thanks for pointing it out! If you really want to sim this item, you can leave your trinket slot empty and use the 'Bonus Stats' section to add the stats.

**Comment by Scubrah** [comment]
Aha - Didn't recognize there was an item level cutoff. Appreciate the reply!
